[project]
name = "boilerplate-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "fastmcp>=2.14.1",
]

[tool.uv]
package = true
